// 128x64
const velocimetro = atob(
  "gEABAAAAAAAAH/+AAAAAAAAAAAAAAAAAAf//+AAAAAAAAAAAAAAAAAf///4AAAAAAAAAAAAAAAAf4AB/gAAAAAAAAAAAAAAAfg//B+AAAAAAAAAAAAAAAfh//+H4AAAAAAAAAAAAAAPj///8fAAAAAAAAAAAAAAHz/Bg/z4AAAAAAAAAAAAADx+AYB+PAAAAAAAAAAAAAB5+AGAH54AAAAAAAAAAAAA8/gBgB/PAAAAAAAAAAAAAeecAYA554AAAAAAAAAAAAPPGAGAGPPAAAAAAAAAAAAHngAAAAB5wAAAAAAAAAAABzwAAAAAPOAAAAAAAAAAAA94AAAAAB5wAAAAAAAAAAAOcAAAAAAOcAAAAAAAAAAAHOAAAAAABzgAAAAAAAAAAB3gAAAAAAe4AAAAAAAAAAA5+AAAAAAfnAAAAAAAAAAAO/gAAAAAH9wAAAAAAAAAAHOQAAAAAAnOAAAAAAAAAABzgAAAAAABzgAAAAAAAAAAdwAAAAAAAO4AAAAAAAAAAHcAAAAAAADuAAAAAAAAAADnAAAAAAAA5wAAAAAAAAAA7gAAAAAAAHcAAAAAAAAAAO4AAAGAAAB3AAAAAAAAAADuAAAH4AAAdwAAAAAAAAAA7gAAD/AAAHcAAAAAAAAAAO4AAA/wAAB3AAAAAAAAAADv+AAf+AAf9wAAAAAAAAAA7/gAH/gAH/cAAAAAAAAAAO4AAA/wAAB3AAAAAAAAAADuAAAP8AAAdwAAAAAAAAAA7gAAB+AAAHcAAAAAAAAAAO4AAAGAAAB3AAAAAAAAAADuAAAAAAAAdwAAAAAAAAAA5wAAAAAAAOcAAAAAAAAAAHcAAAAAAADuAAAAAAAAAAB3AAAAAAAA7gAAAAAAAAAAc4AAAAAAAc4AAAAAAAAAAHOAAAAAAAHOAAAAAAAAAAA7+AAAAAAf3AAAAAAAAAAAOfgD///AH5wAAAAAAAAADh3gD///8Ae4cccAAAAAABEc4A////AHOIoogAAAAAARDnAO7ndwDnAKKIAAAAAAEQ54Du53cB7wCiiAAAAAABEHPA7ud3A84BIogAAAAAARA54P///wecAiKIAAAAAAEQPPD///8PPAQiiAAAAAAA4B54P//8HngPnHAAAAAAAAAPPgAAAHzwAAAAAAAAAAAAB5+AAAH54AAAAAAAAAAAAAPH4AAH48AAAAAAAAAAAAAB8/wAP8+AAAAAAAAAAAAAAPj///8fAAAAAAAAAAAAAAA+H//4fAAAAAAAAAAAAAAAH4P/wfgAAAAAAAAAAAAAAAf4AB/gAAAAAAAAAAAAAAAB////gAAAAAAAAAAAAAAAAH///gAAAAAAAAAAAAAAAAAH/+AAAAAAAAAAA==",
);

const POT = 35;

I2C1.setup();
let oled = require("SSD1306").connect(I2C1);

setInterval(function () {
    let pot = analogRead(POT);
    let angle = pot * 240 - 210
    let rad = angle * Math.PI / 180
    let x0 = 58
    let y0 = 32
    let x1 = 20 * Math.cos(rad) + 58
    let y1 = 20 * Math.sin(rad) + 32
    console.log(angle);
    oled.clear();
    oled.drawImage(velocimetro, 0, 0);
    oled.drawLine(x0, y0, x1, y1);
    oled.flip();
}, 100);
